version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # preserve container's copy
      - .:/app # everything else reference outside filesystem
    stdin_open: true # run in foreground


  # tests:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - /app/node_modules
  #     - .:/app
  #   stdin_open: true # run in foreground
  #   command: ["npm", "run", "test"]
